<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\As_center;
use Illuminate\Database\Seeder;

class AsCenterSeeder extends Seeder
{
    public function run()
    {
        As_center::insert([
            ['name' => 'Central camp', 'district_id' => 1],
            ['name' => 'Lahugala', 'district_id' => 1],
            ['name' => 'Namalthalawa', 'district_id' => 1],
            ['name' => 'Damana / Higurana', 'district_id' => 1],
            ['name' => 'Thottama', 'district_id' => 1],
            ['name' => 'Padiyathalawa', 'district_id' => 1],
            ['name' => 'Mahaoya', 'district_id' => 1],
            ['name' => 'Samanthurei', 'district_id' => 1],
            ['name' => 'Neelavenei', 'district_id' => 1],
            ['name' => 'Akkareipattu(west)', 'district_id' => 1],
            ['name' => 'Malwatta', 'district_id' => 1],
            ['name' => 'Ampara / Uhana', 'district_id' => 1],
            ['name' => 'Kalmunai', 'district_id' => 1],
            ['name' => 'Annamale - Wawalakade', 'district_id' => 1],
            ['name' => 'Pothuwil', 'district_id' => 1],
            ['name' => 'Mayadunna', 'district_id' => 1],
            ['name' => 'Chenkuduiruppu', 'district_id' => 1],
            ['name' => 'Pallanoya', 'district_id' => 1],
            ['name' => 'Eragama', 'district_id' => 1],
            ['name' => 'Panama', 'district_id' => 1],
            ['name' => 'Akkarapattu(east)', 'district_id' => 1],
            ['name' => 'Sayindamardu', 'district_id' => 1],
            ['name' => 'Unknown', 'district_id' => 1],
            ['name' => 'Shrawasthipura', 'district_id' => 2],
            ['name' => 'Anuradhapura', 'district_id' => 2],
            ['name' => 'Kebithigollewa', 'district_id' => 2],
            ['name' => 'Mihinthale', 'district_id' => 2],
            ['name' => 'Padaviparackramapura', 'district_id' => 2],
            ['name' => 'Rajangana south', 'district_id' => 2],
            ['name' => 'Kallanchiya', 'district_id' => 2],
            ['name' => 'Medawachchiya', 'district_id' => 2],
            ['name' => 'Elyapattuwa', 'district_id' => 2],
            ['name' => 'Rabewa', 'district_id' => 2],
            ['name' => 'Gambirigaswewa', 'district_id' => 2],
            ['name' => 'Pemmaduwa', 'district_id' => 2],
            ['name' => 'Rabe wewa', 'district_id' => 2],
            ['name' => 'Ethakada', 'district_id' => 2],
            ['name' => 'Punewa', 'district_id' => 2],
            ['name' => 'Mahaweli pedesa', 'district_id' => 2],
            ['name' => 'Thanthirimale', 'district_id' => 2],
            ['name' => 'Ipalogama', 'district_id' => 2],
            ['name' => 'Muriyakadawela', 'district_id' => 2],
            ['name' => 'Palagala', 'district_id' => 2],
            ['name' => 'Adiyagala', 'district_id' => 2],
            ['name' => 'Madatugama', 'district_id' => 2],
            ['name' => 'Kekirawa', 'district_id' => 2],
            ['name' => 'Palalugaswewa', 'district_id' => 2],
            ['name' => 'Ranorawa', 'district_id' => 2],
            ['name' => 'Nochchiyagama', 'district_id' => 2],
            ['name' => 'Mahaweli pedesa', 'district_id' => 2],
            ['name' => 'Thirappane', 'district_id' => 2],
            ['name' => 'Sivalakulama', 'district_id' => 2],
            ['name' => 'Galenbidunuwewa', 'district_id' => 2],
            ['name' => 'Sayiwalakulama', 'district_id' => 2],
            ['name' => 'Yakella', 'district_id' => 2],
            ['name' => 'Koonwewa', 'district_id' => 2],
            ['name' => 'Kahatagasdigiliya', 'district_id' => 2],
            ['name' => 'Thalawa', 'district_id' => 2],
            ['name' => 'Kattiyawa', 'district_id' => 2],
            ['name' => 'Thabuttegama', 'district_id' => 2],
            ['name' => 'Horowpathana', 'district_id' => 2],
            ['name' => 'Kapugollawa', 'district_id' => 2],
            ['name' => 'Rathmalgahawewa', 'district_id' => 2],
            ['name' => 'Unknown', 'district_id' => 2],
            ['name' => 'Bandarawela', 'district_id' => 3],
            ['name' => 'Ballketuwa', 'district_id' => 3],
            ['name' => 'Diyathalawa', 'district_id' => 3],
            ['name' => 'Kumbalwela', 'district_id' => 3],
            ['name' => 'Diyaluma', 'district_id' => 3],
            ['name' => 'Nikapotha', 'district_id' => 3],
            ['name' => 'Haldummulla', 'district_id' => 3],
            ['name' => 'Rambukpotha', 'district_id' => 3],
            ['name' => 'Madolsima', 'district_id' => 3],
            ['name' => 'Lunugala', 'district_id' => 3],
            ['name' => 'Goradiyawata', 'district_id' => 3],
            ['name' => 'Passara', 'district_id' => 3],
            ['name' => 'Haliela', 'district_id' => 3],
            ['name' => 'Etampitiya', 'district_id' => 3],
            ['name' => 'Kandaketiya', 'district_id' => 3],
            ['name' => 'Ridipana', 'district_id' => 3],
            ['name' => 'Nagadeepa', 'district_id' => 3],
            ['name' => 'Ridimaliyadda', 'district_id' => 3],
            ['name' => 'Mahiyanganaya', 'district_id' => 3],
            ['name' => 'Meegahakivula', 'district_id' => 3],
            ['name' => 'Sapugolla', 'district_id' => 3],
            ['name' => 'Babarapana', 'district_id' => 3],
            ['name' => 'Ambagasdowa', 'district_id' => 3],
            ['name' => 'Kotawera', 'district_id' => 3],
            ['name' => 'Boralanda', 'district_id' => 3],
            ['name' => 'Bogahakubura', 'district_id' => 3],
            ['name' => 'Keppetipola', 'district_id' => 3],
            ['name' => 'Dambawinna', 'district_id' => 3],
            ['name' => 'Maspenna', 'district_id' => 3],
            ['name' => 'Unknown', 'district_id' => 3],
            ['name' => 'Unknown', 'district_id' => 4],
            ['name' => 'Kalladi', 'district_id' => 4],
            ['name' => 'Kanthankudi', 'district_id' => 4],
            ['name' => 'Areipattei', 'district_id' => 4],
            ['name' => 'Mandapattadi', 'district_id' => 4],
            ['name' => 'Walachchenai', 'district_id' => 4],

            ['name' => 'Wantharamulai', 'district_id' => 4],
            ['name' => 'Wakarei', 'district_id' => 4],
            ['name' => 'Kalawanchikudi', 'district_id' => 4],
            ['name' => 'Wellaweli', 'district_id' => 4],
            ['name' => 'Kahathuduwa', 'district_id' => 5],
            ['name' => 'Ayithimale', 'district_id' => 5],
            ['name' => 'Homagama', 'district_id' => 5],
            ['name' => 'Padukka', 'district_id' => 5],
            ['name' => 'Weethara', 'district_id' => 5],
            ['name' => 'Piliyandala (Kesbewa)', 'district_id' => 5],
            ['name' => 'Malabe', 'district_id' => 5],
            ['name' => 'Udahamulla', 'district_id' => 5],
            ['name' => 'Kolonnawa', 'district_id' => 5],
            ['name' => 'Kosgama', 'district_id' => 5],
            ['name' => 'Unknown', 'district_id' => 5],
            ['name' => 'Rathgama', 'district_id' => 6],
            ['name' => 'Pinkanda', 'district_id' => 6],
            ['name' => 'Baddegama', 'district_id' => 6],
            ['name' => 'Waduraba', 'district_id' => 6],
            ['name' => 'Weragoda', 'district_id' => 6],
            ['name' => 'Ambalangoda', 'district_id' => 6],
            ['name' => 'Keradewela', 'district_id' => 6],
            ['name' => 'Urala', 'district_id' => 6],
            ['name' => 'Nagoda', 'district_id' => 6],
            ['name' => 'Gonadeniya', 'district_id' => 6],
            ['name' => 'Yakkalamulla', 'district_id' => 6],
            ['name' => 'Aluthwala', 'district_id' => 6],
            ['name' => 'Batapola', 'district_id' => 6],
            ['name' => 'Elpitiya', 'district_id' => 6],
            ['name' => 'Pinikahana', 'district_id' => 6],
            ['name' => 'Uragasmanhandiya', 'district_id' => 6],
            ['name' => 'Karandeniya', 'district_id' => 6],
            ['name' => 'Ethkadura', 'district_id' => 6],
            ['name' => 'Pahalagamhaya', 'district_id' => 6],
            ['name' => 'Gonagala', 'district_id' => 6],
            ['name' => 'Ahungalla', 'district_id' => 6],
            ['name' => 'Pitigala', 'district_id' => 6],
            ['name' => 'Niyagama', 'district_id' => 6],
            ['name' => 'Thawalama', 'district_id' => 6],
            ['name' => 'Opatha', 'district_id' => 6],
            ['name' => 'Walahanduwa', 'district_id' => 6],
            ['name' => 'Paragoda', 'district_id' => 6],
            ['name' => 'Neluwa', 'district_id' => 6],
            ['name' => 'Pilana', 'district_id' => 6],
            ['name' => 'Labuduwa (no.1)', 'district_id' => 6],
            ['name' => 'Labuduwa (no.2)', 'district_id' => 6],
            ['name' => 'Koggala', 'district_id' => 6],
            ['name' => 'Ahangama', 'district_id' => 6],
            ['name' => 'Kodagoda', 'district_id' => 6],
            ['name' => 'Unknown', 'district_id' => 6],
            ['name' => 'Walpita', 'district_id' => 7],
            ['name' => 'Badalgama', 'district_id' => 7],
            ['name' => 'Maradagahamula', 'district_id' => 7],
            ['name' => 'Pasyala', 'district_id' => 7],
            ['name' => 'Mirigama', 'district_id' => 7],
            ['name' => 'Pallewela', 'district_id' => 7],
            ['name' => 'Adi ambalama', 'district_id' => 7],
            ['name' => 'Katana', 'district_id' => 7],
            ['name' => 'Mudungoda', 'district_id' => 7],
            ['name' => 'Galahitiyawa', 'district_id' => 7],
            ['name' => 'Aluthgama - Bogamuwa', 'district_id' => 7],
            ['name' => 'Minuwangoda', 'district_id' => 7],
            ['name' => 'Mabodala - Minuwangoda', 'district_id' => 7],
            ['name' => 'Udugampola', 'district_id' => 7],
            ['name' => 'Ja ela', 'district_id' => 7],
            ['name' => 'Pamunugama', 'district_id' => 7],
            ['name' => 'Biyagama', 'district_id' => 7],
            ['name' => 'Kelaniya (mahara kadawatha)', 'district_id' => 7],
            ['name' => 'Urapola', 'district_id' => 7],
            ['name' => 'Nittabuwa', 'district_id' => 7],
            ['name' => 'Bemmulla', 'district_id' => 7],
            ['name' => 'Weeke', 'district_id' => 7],
            ['name' => 'Dompe', 'district_id' => 7],
            ['name' => 'Sooriyapaluwa', 'district_id' => 7],
            ['name' => 'Malwathu hiripitiya', 'district_id' => 7],
            ['name' => 'Udupila', 'district_id' => 7],
            ['name' => 'Unknown', 'district_id' => 7],
            ['name' => 'Weerawila', 'district_id' => 8],
            ['name' => 'Beralihela', 'district_id' => 8],
            ['name' => 'Yodakandiya', 'district_id' => 8],
            ['name' => 'Badagiriya', 'district_id' => 8],
            ['name' => 'Meegahajadura', 'district_id' => 8],
            ['name' => 'Agunkolaplessa', 'district_id' => 8],
            ['name' => 'Beliatta', 'district_id' => 8],
            ['name' => 'Lunama', 'district_id' => 8],
            ['name' => 'Netolpitiya', 'district_id' => 8],
            ['name' => 'Ambalanthota', 'district_id' => 8],
            ['name' => 'Moradawana', 'district_id' => 8],
            ['name' => 'Katuwana', 'district_id' => 8],
            ['name' => 'Udayala', 'district_id' => 8],
            ['name' => 'Meegasara', 'district_id' => 8],
            ['name' => 'Walasmulla', 'district_id' => 8],
            ['name' => 'Weeraketiya', 'district_id' => 8],
            ['name' => 'Unknown', 'district_id' => 8],
            ['name' => 'Moronthuduwa', 'district_id' => 10],
            ['name' => 'Padagoda', 'district_id' => 10],
            ['name' => 'Panadura', 'district_id' => 10],
            ['name' => 'Bandaragama', 'district_id' => 10],
            ['name' => 'Pamunugama', 'district_id' => 10],
            ['name' => 'Halkadawila', 'district_id' => 10],

            ['name' => 'Nogoda', 'district_id' => 10],
            ['name' => 'Horana', 'district_id' => 10],
            ['name' => 'Millaniya', 'district_id' => 10],
            ['name' => 'Madurawela', 'district_id' => 10],
            ['name' => 'Bulathsinhala', 'district_id' => 10],
            ['name' => 'Warakagoda', 'district_id' => 10],
            ['name' => 'Pelawatta', 'district_id' => 10],
            ['name' => 'Agalawatta', 'district_id' => 10],
            ['name' => 'Mathugama', 'district_id' => 10],
            ['name' => 'Walagedara', 'district_id' => 10],
            ['name' => 'Dodangoda', 'district_id' => 10],
            ['name' => 'Unknown', 'district_id' => 10],
            ['name' => 'Morayaya', 'district_id' => 11],
            ['name' => 'Ulpathagama', 'district_id' => 11],
            ['name' => 'Kalunthenna', 'district_id' => 11],
            ['name' => 'Vedaruwa', 'district_id' => 11],
            ['name' => 'Nugathenna', 'district_id' => 11],
            ['name' => 'Medamahanuwara', 'district_id' => 11],
            ['name' => 'Dambagahapitiya', 'district_id' => 11],
            ['name' => 'Namadagala', 'district_id' => 11],
            ['name' => 'Karalliyadda', 'district_id' => 11],
            ['name' => 'Yatiwawala', 'district_id' => 11],
            ['name' => 'Gunnepana', 'district_id' => 11],
            ['name' => 'Wawinna', 'district_id' => 11],
            ['name' => 'Manikhinna', 'district_id' => 11],
            ['name' => 'Alawathugoda', 'district_id' => 11],
            ['name' => 'Ankubura', 'district_id' => 11],
            ['name' => 'Thalathuoya', 'district_id' => 11],
            ['name' => 'Galaha', 'district_id' => 11],
            ['name' => 'Marassana', 'district_id' => 11],
            ['name' => 'Wattegama', 'district_id' => 11],
            ['name' => 'Digana', 'district_id' => 11],
            ['name' => 'Kuruduwatta', 'district_id' => 11],
            ['name' => 'Udispattuwa', 'district_id' => 11],
            ['name' => 'Medawala', 'district_id' => 11],
            ['name' => 'Galagedara', 'district_id' => 11],
            ['name' => 'Aludeniya', 'district_id' => 11],
            ['name' => 'Hulugaga', 'district_id' => 11],
            ['name' => 'Hatharaliyadda', 'district_id' => 11],
            ['name' => 'Weliwita', 'district_id' => 11],
            ['name' => 'Edaduwawa', 'district_id' => 11],
            ['name' => 'Giragama', 'district_id' => 11],
            ['name' => 'Manikdiwela', 'district_id' => 11],
            ['name' => 'Rambukpiitya', 'district_id' => 11],
            ['name' => 'Wewala', 'district_id' => 11],
            ['name' => 'Ambanwala', 'district_id' => 11],
            ['name' => 'Pethiyagoda', 'district_id' => 11],
            ['name' => 'Thalawathura', 'district_id' => 11],
            ['name' => 'Imbuldeniya', 'district_id' => 11],
            ['name' => 'Bowala', 'district_id' => 11],
            ['name' => 'Ketawala-lewual', 'district_id' => 11],
            ['name' => 'Alapalawala', 'district_id' => 11],
            ['name' => 'Batugoda', 'district_id' => 11],
            ['name' => 'Unknown', 'district_id' => 11],
            ['name' => 'Paragammana', 'district_id' => 12],
            ['name' => 'Deliwala', 'district_id' => 12],
            ['name' => 'Pinnawala', 'district_id' => 12],
            ['name' => 'Baminiwatta', 'district_id' => 12],
            ['name' => 'Ussapitiya', 'district_id' => 12],
            ['name' => 'Aranayaka', 'district_id' => 12],
            ['name' => 'Dedigama', 'district_id' => 12],
            ['name' => 'Galigamuwa', 'district_id' => 12],
            ['name' => 'Batuwatta', 'district_id' => 12],
            ['name' => 'Ambepussa', 'district_id' => 12],
            ['name' => 'Yatiyanthota', 'district_id' => 12],
            ['name' => 'Ruwanwella', 'district_id' => 12],
            ['name' => 'Deraniyagala', 'district_id' => 12],
            ['name' => 'Panawala', 'district_id' => 12],
            ['name' => 'Unknown', 'district_id' => 12],
            ['name' => 'Kilinochchiya - east', 'district_id' => 13],
            ['name' => 'Kilinochchiya - west', 'district_id' => 13],
            ['name' => 'Ramanadapuram', 'district_id' => 13],
            ['name' => 'Palai', 'district_id' => 13],
            ['name' => 'Pulliyampokkanei', 'district_id' => 13],
            ['name' => 'Uruttipuram', 'district_id' => 13],
            ['name' => 'Akkarayankulam', 'district_id' => 13],
            ['name' => 'Mulankavi', 'district_id' => 13],
            ['name' => 'Punakari', 'district_id' => 13],
            ['name' => 'Unknown', 'district_id' => 13],
            ['name' => 'Tharana', 'district_id' => 14],
            ['name' => 'Deegalla', 'district_id' => 14],
            ['name' => 'Weerabugedara', 'district_id' => 14],
            ['name' => 'Kudagalgamuwa', 'district_id' => 14],
            ['name' => 'Wellawa', 'district_id' => 14],
            ['name' => 'Rambadagalla', 'district_id' => 14],
            ['name' => 'Melsiripura', 'district_id' => 14],
            ['name' => 'Ibbagamuwa', 'district_id' => 14],
            ['name' => 'Dodamgaslanda', 'district_id' => 14],
            ['name' => 'Weerawella', 'district_id' => 14],
            ['name' => 'Karadagolla', 'district_id' => 14],
            ['name' => 'Mawathagama', 'district_id' => 14],
            ['name' => 'Kurunegala', 'district_id' => 14],
            ['name' => 'Boyagane', 'district_id' => 14],
            ['name' => 'Polgahawela', 'district_id' => 14],
            ['name' => 'Pothuhera', 'district_id' => 14],
            ['name' => 'Narammala', 'district_id' => 14],
            ['name' => 'Kithalawa', 'district_id' => 14],
            ['name' => 'Wewegama', 'district_id' => 14],
            ['name' => 'Yakwila', 'district_id' => 14],
            ['name' => 'Welpalla', 'district_id' => 14],

            ['name' => 'Hamangalla', 'district_id' => 14],
            ['name' => 'Udubaddawa', 'district_id' => 14],
            ['name' => 'Horombawa', 'district_id' => 14],
            ['name' => 'Mahachchimulla', 'district_id' => 14],
            ['name' => 'Dummalasooriya', 'district_id' => 14],
            ['name' => 'Dambadeniya', 'district_id' => 14],
            ['name' => 'Kumbukgete', 'district_id' => 14],
            ['name' => 'Ganewatta', 'district_id' => 14],
            ['name' => 'Bingiriya', 'district_id' => 14],
            ['name' => 'Paduwasnuwara', 'district_id' => 14],
            ['name' => 'Unknown', 'district_id' => 14],
            ['name' => 'Pallepola', 'district_id' => 16],
            ['name' => 'Wahakotte', 'district_id' => 16],
            ['name' => 'Ilukkubara', 'district_id' => 16],
            ['name' => 'Hattota amuna', 'district_id' => 16],
            ['name' => 'Hettipola', 'district_id' => 16],
            ['name' => 'Hadungamuwa', 'district_id' => 16],
            ['name' => 'Raththota', 'district_id' => 16],
            ['name' => 'Palapathwala', 'district_id' => 16],
            ['name' => 'Bandarapola', 'district_id' => 16],
            ['name' => 'Werugama', 'district_id' => 16],
            ['name' => 'Yatawatta', 'district_id' => 16],
            ['name' => 'Walewela', 'district_id' => 16],
            ['name' => 'Thenna', 'district_id' => 16],
            ['name' => 'Elkaduwa', 'district_id' => 16],
            ['name' => 'Ukuwela', 'district_id' => 16],
            ['name' => 'Kimbissa', 'district_id' => 16],
            ['name' => 'Kongahawela', 'district_id' => 16],
            ['name' => 'Hunuketaela', 'district_id' => 16],
            ['name' => 'Naula', 'district_id' => 16],
            ['name' => 'Dambulla', 'district_id' => 16],
            ['name' => 'Galewela', 'district_id' => 16],
            ['name' => 'Devahuwa', 'district_id' => 16],
            ['name' => 'Unknown', 'district_id' => 16],
            ['name' => 'Madihe - godagama', 'district_id' => 17],
            ['name' => 'Kekunadura', 'district_id' => 17],
            ['name' => 'Dandeniya', 'district_id' => 17],
            ['name' => 'Dikwella', 'district_id' => 17],
            ['name' => 'Thalalla', 'district_id' => 17],
            ['name' => 'Kirinda - puhulwella', 'district_id' => 17],
            ['name' => 'Hakmana', 'district_id' => 17],
            ['name' => 'Deyiyandara', 'district_id' => 17],
            ['name' => 'Mirissa', 'district_id' => 17],
            ['name' => 'Weligama', 'district_id' => 17],
            ['name' => 'Kananke', 'district_id' => 17],
            ['name' => 'Malimbada', 'district_id' => 17],
            ['name' => 'Akuressa', 'district_id' => 17],
            ['name' => 'Wilpita', 'district_id' => 17],
            ['name' => 'Ransegoda', 'district_id' => 17],
            ['name' => 'Deniyaya', 'district_id' => 17],
            ['name' => 'Kaburupitiya', 'district_id' => 17],
            ['name' => 'Medawiyangoda', 'district_id' => 17],
            ['name' => 'Morawaka', 'district_id' => 17],
            ['name' => 'Urubokka', 'district_id' => 17],
            ['name' => 'Beralapanathara', 'district_id' => 17],
            ['name' => 'Pasgoda', 'district_id' => 17],
            ['name' => 'Unknown', 'district_id' => 17],
            ['name' => 'Monaragala', 'district_id' => 18],
            ['name' => 'Badalkubura', 'district_id' => 18],
            ['name' => 'Higurukaduwa', 'district_id' => 18],
            ['name' => 'Siyabalanduwa', 'district_id' => 18],
            ['name' => 'Ethimale', 'district_id' => 18],
            ['name' => 'Bibila', 'district_id' => 18],
            ['name' => 'Kotagama', 'district_id' => 18],
            ['name' => 'Dambagalla', 'district_id' => 18],
            ['name' => 'Thanamalwila', 'district_id' => 18],
            ['name' => 'Medagama', 'district_id' => 18],
            ['name' => 'Katharagama', 'district_id' => 18],
            ['name' => 'Aluthwewa', 'district_id' => 18],
            ['name' => 'Thelulla', 'district_id' => 18],
            ['name' => 'Wellawaya', 'district_id' => 18],
            ['name' => 'Buttala', 'district_id' => 18],
            ['name' => 'Unknown', 'district_id' => 18],
            ['name' => 'Lidula', 'district_id' => 20],
            ['name' => 'Nuwaraeliya', 'district_id' => 20],
            ['name' => 'Helboda', 'district_id' => 20],
            ['name' => 'Harangala', 'district_id' => 20],
            ['name' => 'Mathurata', 'district_id' => 20],
            ['name' => 'Maldeniya', 'district_id' => 20],
            ['name' => 'Pudalu - oya', 'district_id' => 20],
            ['name' => 'Ginigathhena', 'district_id' => 20],
            ['name' => 'Vidulipura', 'district_id' => 20],
            ['name' => 'Mandaramnuwara', 'district_id' => 20],
            ['name' => 'Pallebowala', 'district_id' => 20],
            ['name' => 'Karalliyadda', 'district_id' => 20],
            ['name' => 'Rikillagaskada', 'district_id' => 20],
            ['name' => 'Haguranketha', 'district_id' => 20],
            ['name' => 'Bulugahapitiya', 'district_id' => 20],
            ['name' => 'Munwatta', 'district_id' => 20],
            ['name' => 'Their pehe', 'district_id' => 20],
            ['name' => 'Rupaha', 'district_id' => 20],
            ['name' => 'Ragala', 'district_id' => 20],
            ['name' => 'Walapane', 'district_id' => 20],
            ['name' => 'Nildandahinna', 'district_id' => 20],
            ['name' => 'Unknown', 'district_id' => 20],
            ['name' => 'Elahera', 'district_id' => 21],
            ['name' => 'Higurakgoda', 'district_id' => 21],
            ['name' => 'Medirigiriya', 'district_id' => 21],
            ['name' => 'Thamankaduwa', 'district_id' => 21],
            ['name' => 'Lankapura', 'district_id' => 21],

            ['name' => 'Dimbulagala', 'district_id' => 21],
            ['name' => 'Unknown', 'district_id' => 21],
            ['name' => 'Mahawewa', 'district_id' => 22],
            ['name' => 'Nattandiya-Thabbowa', 'district_id' => 22],
            ['name' => 'Haladuwana', 'district_id' => 22],
            ['name' => 'Nainamadama', 'district_id' => 22],
            ['name' => 'Munneswaram', 'district_id' => 22],
            ['name' => 'Madampe', 'district_id' => 22],
            ['name' => 'Mahakumbukkadawa', 'district_id' => 22],
            ['name' => 'Rajakadaluwa', 'district_id' => 22],
            ['name' => 'Wanathawilluwa', 'district_id' => 22],
            ['name' => 'Palakuda', 'district_id' => 22],
            ['name' => 'Madurankuli', 'district_id' => 22],
            ['name' => 'Puliyankulam', 'district_id' => 22],
            ['name' => 'Thabbowa (Puttalam)', 'district_id' => 22],
            ['name' => 'Inginimitiya', 'district_id' => 22],
            ['name' => 'Nawagattegama', 'district_id' => 22],
            ['name' => 'Anamaduwa', 'district_id' => 22],
            ['name' => 'Serukele', 'district_id' => 22],
            ['name' => 'Unknown', 'district_id' => 22],
            ['name' => 'Bambarabotuwa', 'district_id' => 23],
            ['name' => 'Gilimale', 'district_id' => 23],
            ['name' => 'Kalawana', 'district_id' => 23],
            ['name' => 'Kuruwita', 'district_id' => 23],
            ['name' => 'Marapana', 'district_id' => 23],
            ['name' => 'Opanayaka', 'district_id' => 23],
            ['name' => 'Pambahinna', 'district_id' => 23],
            ['name' => 'Damana east', 'district_id' => 23],
            ['name' => 'Ayagama', 'district_id' => 23],
            ['name' => 'Rathmalwinna', 'district_id' => 23],
            ['name' => 'Pothupitiya', 'district_id' => 23],
            ['name' => 'Kahawatta', 'district_id' => 23],
            ['name' => 'Pelmadulla', 'district_id' => 23],
            ['name' => 'Opanayaka west', 'district_id' => 23],
            ['name' => 'Kalthota', 'district_id' => 23],
            ['name' => 'Godakawela', 'district_id' => 23],
            ['name' => 'Embilipitiya', 'district_id' => 23],
            ['name' => 'Kalthota south', 'district_id' => 23],
            ['name' => 'Nivithigala', 'district_id' => 23],
            ['name' => 'Ehaliyagoda', 'district_id' => 23],
            ['name' => 'Thimboketiya', 'district_id' => 23],
            ['name' => 'Ambewila', 'district_id' => 23],
            ['name' => 'Weligepola', 'district_id' => 23],
            ['name' => 'Panamure', 'district_id' => 23],
            ['name' => 'Kolonna', 'district_id' => 23],
            ['name' => 'Rassagala', 'district_id' => 23],
            ['name' => 'Godakawela east', 'district_id' => 23],
            ['name' => 'Rathmalwinna', 'district_id' => 23],
            ['name' => 'Rathnapura', 'district_id' => 23],
            ['name' => 'Ayagama west', 'district_id' => 23],
            ['name' => 'Nivithigala west', 'district_id' => 23],
            ['name' => 'Nivithigala east', 'district_id' => 23],
            ['name' => 'Marapana east', 'district_id' => 23],
            ['name' => 'Dodampe', 'district_id' => 23],
            ['name' => 'Kiriella', 'district_id' => 23],
            ['name' => 'Namaldeniya', 'district_id' => 23],
            ['name' => 'Damahan west', 'district_id' => 23],
            ['name' => 'Kuruwita', 'district_id' => 23],
            ['name' => 'Pallebedda', 'district_id' => 23],
            ['name' => 'Unknown', 'district_id' => 23],
            ['name' => 'Kantale', 'district_id' => 24],
            ['name' => 'Agbopura', 'district_id' => 24],
            ['name' => 'Van ela', 'district_id' => 24],
            ['name' => 'Serunuwara', 'district_id' => 24],
            ['name' => 'Mollipothana', 'district_id' => 24],
            ['name' => 'Padavi siripura', 'district_id' => 24],
            ['name' => 'Gomarankadawala', 'district_id' => 24],
            ['name' => 'Pankulam', 'district_id' => 24],
            ['name' => 'Thampalakamam', 'district_id' => 24],
            ['name' => 'Uppuweli', 'district_id' => 24],
            ['name' => 'Kuchchuweli', 'district_id' => 24],
            ['name' => 'Kinya', 'district_id' => 24],
            ['name' => 'Thopur', 'district_id' => 24],
            ['name' => 'Kiliweddi', 'district_id' => 24],
            ['name' => 'Munampodiweddi', 'district_id' => 24],
            ['name' => 'Sampalathivu', 'district_id' => 24],
            ['name' => 'Nilaveli', 'district_id' => 24],
            ['name' => 'Sampur', 'district_id' => 24],
            ['name' => 'Muthur', 'district_id' => 24],
            ['name' => 'Echchailampathei', 'district_id' => 24],
            ['name' => 'Pulmudei', 'district_id' => 24],
            ['name' => 'Unknown', 'district_id' => 24],
            ['name' => 'Chawakachcheri', 'district_id' => 9],
            ['name' => 'Unknown', 'district_id' => 9],
            ['name' => 'Mannar', 'district_id' => 15],
            ['name' => 'Unknown', 'district_id' => 15],
            ['name' => 'Puthukuduirippu', 'district_id' => 19],
            ['name' => 'Unknown', 'district_id' => 19],
            ['name' => 'Vavuniya', 'district_id' => 25],
            ['name' => 'Unknown', 'district_id' => 25],
            ['name' => 'Mahaweli areas', 'district_id' => 2],
            ['name' => 'Mahaweli areas', 'district_id' => 21],
            ['name' => 'Mahaweli areas', 'district_id' => 3],
            ['name' => 'Higurana', 'district_id' => 1],
            ['name' => 'Nindavur', 'district_id' => 1],
            ['name' => 'Palamuna', 'district_id' => 1],
            ['name' => 'Karthivu', 'district_id' => 1],
            ['name' => 'Thambuvil', 'district_id' => 1],
            ['name' => 'Lahugala', 'district_id' => 1],
            ['name' => 'Pothuvil', 'district_id' => 1],

            ['name' => 'Dimbulagala', 'district_id' => 21],
            ['name' => 'Unknown', 'district_id' => 21],
            ['name' => 'Mahawewa', 'district_id' => 22],
            ['name' => 'Nattandiya-Thabbowa', 'district_id' => 22],
            ['name' => 'Haladuwana', 'district_id' => 22],
            ['name' => 'Nainamadama', 'district_id' => 22],
            ['name' => 'Munneswaram', 'district_id' => 22],
            ['name' => 'Madampe', 'district_id' => 22],
            ['name' => 'Mahakumbukkadawa', 'district_id' => 22],
            ['name' => 'Rajakadaluwa', 'district_id' => 22],
            ['name' => 'Wanathawilluwa', 'district_id' => 22],
            ['name' => 'Palakuda', 'district_id' => 22],
            ['name' => 'Madurankuli', 'district_id' => 22],
            ['name' => 'Puliyankulam', 'district_id' => 22],
            ['name' => 'Thabbowa (Puttalam)', 'district_id' => 22],
            ['name' => 'Inginimitiya', 'district_id' => 22],
            ['name' => 'Nawagattegama', 'district_id' => 22],
            ['name' => 'Anamaduwa', 'district_id' => 22],
            ['name' => 'Serukele', 'district_id' => 22],
            ['name' => 'Unknown', 'district_id' => 22],
            ['name' => 'Bambarabotuwa', 'district_id' => 23],
            ['name' => 'Gilimale', 'district_id' => 23],
            ['name' => 'Kalawana', 'district_id' => 23],
            ['name' => 'Kuruwita', 'district_id' => 23],
            ['name' => 'Marapana', 'district_id' => 23],
            ['name' => 'Opanayaka', 'district_id' => 23],
            ['name' => 'Pambahinna', 'district_id' => 23],
            ['name' => 'Damana east', 'district_id' => 23],
            ['name' => 'Ayagama', 'district_id' => 23],
            ['name' => 'Rathmalwinna', 'district_id' => 23],
            ['name' => 'Pothupitiya', 'district_id' => 23],
            ['name' => 'Kahawatta', 'district_id' => 23],
            ['name' => 'Pelmadulla', 'district_id' => 23],
            ['name' => 'Opanayaka west', 'district_id' => 23],
            ['name' => 'Kalthota', 'district_id' => 23],
            ['name' => 'Godakawela', 'district_id' => 23],
            ['name' => 'Embilipitiya', 'district_id' => 23],
            ['name' => 'Kalthota south', 'district_id' => 23],
            ['name' => 'Nivithigala', 'district_id' => 23],
            ['name' => 'Ehaliyagoda', 'district_id' => 23],
            ['name' => 'Thimboketiya', 'district_id' => 23],
            ['name' => 'Ambewila', 'district_id' => 23],
            ['name' => 'Weligepola', 'district_id' => 23],
            ['name' => 'Panamure', 'district_id' => 23],
            ['name' => 'Kolonna', 'district_id' => 23],
            ['name' => 'Rassagala', 'district_id' => 23],
            ['name' => 'Godakawela east', 'district_id' => 23],
            ['name' => 'Rathmalwinna', 'district_id' => 23],
            ['name' => 'Rathnapura', 'district_id' => 23],
            ['name' => 'Ayagama west', 'district_id' => 23],
            ['name' => 'Nivithigala west', 'district_id' => 23],
            ['name' => 'Nivithigala east', 'district_id' => 23],
            ['name' => 'Marapana east', 'district_id' => 23],
            ['name' => 'Dodampe', 'district_id' => 23],
            ['name' => 'Kiriella', 'district_id' => 23],
            ['name' => 'Namaldeniya', 'district_id' => 23],
            ['name' => 'Damahan west', 'district_id' => 23],
            ['name' => 'Kuruwita', 'district_id' => 23],
            ['name' => 'Pallebedda', 'district_id' => 23],
            ['name' => 'Unknown', 'district_id' => 23],
            ['name' => 'Kantale', 'district_id' => 24],
            ['name' => 'Agbopura', 'district_id' => 24],
            ['name' => 'Van ela', 'district_id' => 24],
            ['name' => 'Serunuwara', 'district_id' => 24],
            ['name' => 'Mollipothana', 'district_id' => 24],
            ['name' => 'Padavi siripura', 'district_id' => 24],
            ['name' => 'Gomarankadawala', 'district_id' => 24],
            ['name' => 'Pankulam', 'district_id' => 24],
            ['name' => 'Thampalakamam', 'district_id' => 24],
            ['name' => 'Uppuweli', 'district_id' => 24],
            ['name' => 'Kuchchuweli', 'district_id' => 24],
            ['name' => 'Kinya', 'district_id' => 24],
            ['name' => 'Thopur', 'district_id' => 24],
            ['name' => 'Kiliweddi', 'district_id' => 24],
            ['name' => 'Munampodiweddi', 'district_id' => 24],
            ['name' => 'Sampalathivu', 'district_id' => 24],
            ['name' => 'Nilaveli', 'district_id' => 24],
            ['name' => 'Sampur', 'district_id' => 24],
            ['name' => 'Muthur', 'district_id' => 24],
            ['name' => 'Echchailampathei', 'district_id' => 24],
            ['name' => 'Pulmudei', 'district_id' => 24],
            ['name' => 'Unknown', 'district_id' => 24],
            ['name' => 'Chawakachcheri', 'district_id' => 9],
            ['name' => 'Unknown', 'district_id' => 9],
            ['name' => 'Mannar', 'district_id' => 15],
            ['name' => 'Unknown', 'district_id' => 15],
            ['name' => 'Puthukuduirippu', 'district_id' => 19],
            ['name' => 'Unknown', 'district_id' => 19],
            ['name' => 'Vavuniya', 'district_id' => 25],
            ['name' => 'Unknown', 'district_id' => 25],
            ['name' => 'Mahaweli areas', 'district_id' => 2],
            ['name' => 'Mahaweli areas', 'district_id' => 21],
            ['name' => 'Mahaweli areas', 'district_id' => 3],
            ['name' => 'Higurana', 'district_id' => 1],
            ['name' => 'Nindavur', 'district_id' => 1],
            ['name' => 'Palamuna', 'district_id' => 1],
            ['name' => 'Karthivu', 'district_id' => 1],
            ['name' => 'Thambuvil', 'district_id' => 1],
            ['name' => 'Lahugala', 'district_id' => 1],
            ['name' => 'Pothuvil', 'district_id' => 1],
            ['name' => 'Pallanoya', 'district_id' => 1],
            ['name' => 'Attalachena', 'district_id' => 1],
            ['name' => 'Panama', 'district_id' => 1],
            ['name' => 'Madanagama', 'district_id' => 1],
            ['name' => 'Komari', 'district_id' => 1],
            ['name' => 'Malwatta', 'district_id' => 1],
            ['name' => 'Sammanthura', 'district_id' => 1],
            ['name' => 'Wawalakade', 'district_id' => 1],
            ['name' => 'Dehiattakandiya', 'district_id' => 1],
            ['name' => 'Kesbewa', 'district_id' => 5],
            ['name' => 'Kotte', 'district_id' => 5],
            ['name' => 'Henarathgoda', 'district_id' => 7],
            ['name' => 'Yakkala', 'district_id' => 7],
            ['name' => 'Baduraliya', 'district_id' => 10],
            ['name' => 'Iththepana', 'district_id' => 10],
            ['name' => 'Ingiriya', 'district_id' => 10],
            ['name' => 'Kananwila', 'district_id' => 10],
            ['name' => 'Yatiwawala', 'district_id' => 11],
            ['name' => 'Theldeniya', 'district_id' => 11],
            ['name' => 'Gampola', 'district_id' => 11],
            ['name' => 'Delpitiya', 'district_id' => 11],
            ['name' => 'Medapitiya', 'district_id' => 11],
            ['name' => 'Mulgama', 'district_id' => 11],
            ['name' => 'Alugolla', 'district_id' => 16],
            ['name' => 'Laggala pallegama', 'district_id' => 16],
            ['name' => 'Kadapola', 'district_id' => 20],
            ['name' => 'Kotavehera', 'district_id' => 14],
            ['name' => 'Mahagirilla', 'district_id' => 14],
            ['name' => 'Rasnayakapura', 'district_id' => 14],
            ['name' => 'Nikaweratiya', 'district_id' => 14],
            ['name' => 'Kobeigane', 'district_id' => 14],
            ['name' => 'Divullegoda', 'district_id' => 14],
            ['name' => 'Mahananneriya', 'district_id' => 14],
            ['name' => 'Galgamuwa', 'district_id' => 14],
            ['name' => 'Ehatuwewa', 'district_id' => 14],
            ['name' => 'Rajanganaya', 'district_id' => 14],
            ['name' => 'Thabutta', 'district_id' => 14],
            ['name' => 'Ambanpola', 'district_id' => 14],
            ['name' => 'Nagollagama', 'district_id' => 14],
            ['name' => 'Mahawa', 'district_id' => 14],
            ['name' => 'Rambe', 'district_id' => 14],
            ['name' => 'Moragollagama', 'district_id' => 14],
            ['name' => 'Madahapola', 'district_id' => 14],
            ['name' => 'Nathagane', 'district_id' => 14],
            ['name' => 'Wariyapola', 'district_id' => 14],
            ['name' => 'Avulegama', 'district_id' => 14],
            ['name' => 'Kanogama', 'district_id' => 14],
            ['name' => 'Munamaldeniya', 'district_id' => 14],
            ['name' => 'Kuliyapitiya', 'district_id' => 14],
            ['name' => 'Alawuwa', 'district_id' => 14],
            ['name' => 'Kudawewa', 'district_id' => 22],
            ['name' => 'Puttalam', 'district_id' => 22],
            ['name' => 'Maradankadawala', 'district_id' => 2],
            ['name' => 'Parangiyawadiya', 'district_id' => 2],
            ['name' => 'Neegampaha', 'district_id' => 2],
            ['name' => 'Eppawala', 'district_id' => 2],
            ['name' => 'Newtown', 'district_id' => 21],
            ['name' => 'Manampitiya', 'district_id' => 21],
            ['name' => 'Sewagama', 'district_id' => 21],
            ['name' => 'Girithale', 'district_id' => 21],
            ['name' => 'Bakamuna', 'district_id' => 21],
            ['name' => 'Pulasthigama', 'district_id' => 21],
            ['name' => 'Galamuna', 'district_id' => 21],
            ['name' => 'Viyaluwa', 'district_id' => 3],
            ['name' => 'Bathmedilla', 'district_id' => 3],
            ['name' => 'Karametiya', 'district_id' => 3],
            ['name' => 'Thennakubura', 'district_id' => 3],
            ['name' => 'Yatipalatha', 'district_id' => 3],
            ['name' => 'Uva paranagama', 'district_id' => 3],
            ['name' => 'Okkampitiya', 'district_id' => 18],
            ['name' => 'Elapatha', 'district_id' => 23],
            ['name' => 'Uppuweli', 'district_id' => 24],
            ['name' => 'Sambalthivu', 'district_id' => 24],
            ['name' => 'Kuchchaweli', 'district_id' => 24],
            ['name' => 'Pulmude', 'district_id' => 24],
            ['name' => 'Kinniya', 'district_id' => 24],
            ['name' => 'Kurunwankarni', 'district_id' => 24],
            ['name' => 'Thampalagamam', 'district_id' => 24],
            ['name' => 'Mullipothana', 'district_id' => 24],
            ['name' => 'Mutthur', 'district_id' => 24],
            ['name' => 'Sampur', 'district_id' => 24],
            ['name' => 'Thopur', 'district_id' => 24],
            ['name' => 'Kiliveddi', 'district_id' => 24],
            ['name' => 'Munnampodivaddei', 'district_id' => 24],
            ['name' => 'Eevvalampannei', 'district_id' => 24],
            ['name' => 'Nedunkerni', 'district_id' => 25],
            ['name' => 'Kanagarayankulam', 'district_id' => 25],
            ['name' => 'Kovilkulam', 'district_id' => 25],
            ['name' => 'Pampaimadu', 'district_id' => 25],
            ['name' => 'Omanthei', 'district_id' => 25],
            ['name' => 'Ulukkulam', 'district_id' => 25],
            ['name' => 'Veddikulama', 'district_id' => 25],
            ['name' => 'Madukanda', 'district_id' => 25],
            ['name' => 'Kainadi', 'district_id' => 9],
            ['name' => 'Nallur', 'district_id' => 9],
            ['name' => 'Velanei', 'district_id' => 9],
            ['name' => 'Punkuduthivu', 'district_id' => 9],
            ['name' => 'Tholpuram', 'district_id' => 9],
            ['name' => 'Kerimalei', 'district_id' => 9],
            ['name' => 'Uduvil', 'district_id' => 9],

            ['name' => 'Puttur', 'district_id' => 9],
            ['name' => 'Urumpirai', 'district_id' => 9],
            ['name' => 'Puloli', 'district_id' => 9],
            ['name' => 'Amban', 'district_id' => 9],
            ['name' => 'Kareinagar', 'district_id' => 9],
            ['name' => 'Oddusuddan', 'district_id' => 19],
            ['name' => 'Olumadu', 'district_id' => 19],
            ['name' => 'Thunukkai', 'district_id' => 19],
            ['name' => 'Pandiyankulam', 'district_id' => 19],
            ['name' => 'Kamulmunai', 'district_id' => 19],
            ['name' => 'Mulliyawalei', 'district_id' => 19],
            ['name' => 'Kokkuthoduwai', 'district_id' => 19],
            ['name' => 'Alambil', 'district_id' => 19],
            ['name' => 'Udayarkaddu', 'district_id' => 19],
            ['name' => 'Ayitthiyamalei', 'district_id' => 4],
            ['name' => 'Eravur', 'district_id' => 4],
            ['name' => 'Karadiyanaru', 'district_id' => 4],
            ['name' => 'Palugamam', 'district_id' => 4],
            ['name' => 'Kokkadicholei', 'district_id' => 4],
            ['name' => 'Mandur', 'district_id' => 4],
            ['name' => 'Kiran', 'district_id' => 4],
            ['name' => 'Thanthamalei', 'district_id' => 4],
            ['name' => 'Murukkan', 'district_id' => 15],
            ['name' => 'Olankulam', 'district_id' => 15],
            ['name' => 'Alkadiveli', 'district_id' => 15],
            ['name' => 'Nanathan', 'district_id' => 15],
            ['name' => 'Mannei', 'district_id' => 15],
            ['name' => 'Iluppakaduvei', 'district_id' => 15],
            ['name' => 'Veddathalathivu', 'district_id' => 15],
            ['name' => 'Palampadi', 'district_id' => 15],
            ['name' => 'Iraneiilattikulam', 'district_id' => 15],
            ['name' => 'Potkerni', 'district_id' => 15],
            ['name' => 'Silvawathurei', 'district_id' => 15],
            ['name' => 'Yatiyana', 'district_id' => 17],

        ]);
    }
}
