<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Collectors List - {{ $region }} - {{ $seasonName }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #000;
        }

        h2,
        h3 {
            text-align: center;
            margin: 0;
        }

        h2 {
            margin-bottom: 5px;
            text-transform: uppercase;
        }

        .meta-info {
            text-align: center;
            font-size: 13px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            page-break-inside: avoid;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 6px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .district-row {
            background-color: #eaeaea;
            font-weight: bold;
            text-align: left;
        }

        .footer {
            text-align: right;
            margin-top: 10px;
            font-size: 11px;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>

<body>

    <h2>Department of Agriculture - Plant Protection Service</h2>
    <h3>Collectors List Report</h3>
    <div class="meta-info">
        <strong>Region:</strong> {{ $region }} |
        <strong>Season:</strong> {{ $seasonName }} |
        <strong>Generated on:</strong> {{ now()->format('Y-m-d H:i') }}
    </div>

    @foreach ($data as $districtData)
        <table>
            <tr class="district-row">
                <td colspan="8">{{ $districtData['district'] }}</td>
            </tr>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>ASC</th>
                <th>AI Range</th>
                <th>Phone</th>
                <th>Joined Date</th>
                <th>Email</th>
                <th>Season</th>
            </tr>

            @foreach ($districtData['collectors'] as $index => $collector)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $collector[0] ?? '-' }}</td>
                    <td>{{ $collector[1] ?? '-' }}</td>
                    <td>{{ $collector[2] ?? '-' }}</td>
                    <td>{{ $collector[3] ?? '-' }}</td>
                    <td>{{ $collector[4] ?? '-' }}</td>
                    <td>{{ $collector[5] ?? '-' }}</td>
                    <td>{{ $collector[7] ?? '-' }}</td>
                </tr>
            @endforeach
        </table>

        <br>
    @endforeach

    <div class="footer">
        Generated by National Pest Surveillance System (NPSS)
    </div>

</body>

</html>
